# Numpy Arrays
(NumPy stands for Numerical Python)


NumPy is a Python library used for working with arrays.It also has functions for working in domain of linear algebra and matrices.


**Why Use NumPy?**


In Python we have lists that serve the purpose of arrays, but they are slow to process.
**NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.**
The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.


In [ ]:
!pip install --upgrade pip
!pip install numpy

In [ ]:
#Checking NumPy Version
import numpy as np

print(np.__version__)

2.3.3


# array object
* 1-D
* 2-D
* 3-D ...n-D

In [12]:
#1-D
arr1=np.array([1,2,3,4])
arr1


array([1, 2, 3, 4])

In [8]:
#2-d
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#3-d
arr3=np.array([    [   [1,2,3],[4,5,6]    ] ,  [    [5,6,7]   ,  [10,77,55]    ]          ])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 5,  6,  7],
        [10, 77, 55]]])

![](https://nustat.github.io/DataScience_Intro_python/Datasets/numpy_image.png)

In [24]:
raw1=[1,2,3]
raw2=[4,5,6]
raw3=[7,8,9]
big_array=np.array([raw1,raw2,raw3])
big_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


# Some important NumPy array creation functions
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Function</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>array</code></td>
<td style="text-align: left;">Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>asarray</code></td>
<td style="text-align: left;">Convert input to ndarray, but do not copy if the input is already an ndarray</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>arange</code></td>
<td style="text-align: left;">Like the built-in <code>range</code> but returns an ndarray instead of a list</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>ones, ones_like</code></td>
<td style="text-align: left;">Produce an array of all 1s with the given shape and data type; <code>ones_like</code> takes another array and produces a <code>ones</code> array of the same shape and data type</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>zeros, zeros_like</code></td>
<td style="text-align: left;">Like <code>ones</code> and <code>ones_like</code> but producing arrays of 0s instead</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>empty, empty_like</code></td>
<td style="text-align: left;">Create new arrays by allocating new memory, but do not populate with any values like <code>ones</code> and <code>zeros</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>full, full_like</code></td>
<td style="text-align: left;">Produce an array of the given shape and data type with all values set to the indicated "fill value"; <code>full_like</code> takes another array and produces a filled array of the same shape and data type</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>eye, identity</code></td>
<td style="text-align: left;">Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)</td>
</tr>
</tbody>
</table>

In [ ]:
existing_array = np.array([1, 2, 3])
new_view = np.asarray(existing_array)

# هنا new_view تشير لنفس مكان existing_array في الذاكرة
print(new_view is existing_array)

# The Differnce between numpy Arange & python range

<table border="1" style="width:100%; border-collapse: collapse; font-family: Arial, sans-serif;">
  <thead>
    <tr style= text-align: left;">
      <th style="padding: 10px;">Feature</th>
      <th style="padding: 10px;">range (Built-in Python)</th>
      <th style="padding: 10px;">np.arange (NumPy Library)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding: 10px; font-weight: bold;">Return Type</td>
      <td style="padding: 10px;">Returns a <b>range object</b> (Lazy iterator).</td>
      <td style="padding: 10px;">Returns a <b>numpy.ndarray</b> (Memory-backed array).</td>
    </tr>
    <tr>
      <td style="padding: 10px; font-weight: bold;">Data Types</td>
      <td style="padding: 10px;">Supports only <b>Integers</b> for start, stop, and step.</td>
      <td style="padding: 10px;">Supports <b>Integers and Floats</b> (Floating-point numbers).</td>
    </tr>
    <tr>
      <td style="padding: 10px; font-weight: bold;">Memory Efficiency</td>
      <td style="padding: 10px;">High; generates numbers on-the-fly.</td>
      <td style="padding: 10px;">Lower for very large sequences; stores all elements in memory.</td>
    </tr>
    <tr>
      <td style="padding: 10px; font-weight: bold;">Performance</td>
      <td style="padding: 10px;">Slower for heavy numerical computations.</td>
      <td style="padding: 10px;">Highly optimized for <b>vectorized</b> computations.</td>
    </tr>
    <tr>
      <td style="padding: 10px; font-weight: bold;">Vectorization</td>
      <td style="padding: 10px;">Not supported; requires loops for math operations.</td>
      <td style="padding: 10px;">Supports <b>Element-wise</b> mathematical operations.</td>
    </tr>
  </tbody>
</table>

# ```np.arange``` & range

**in arange we can use floting step** `arange(start,stop,step)`

In [23]:
range_step=np.arange(0,5,.5)
print(range_step)
rang_list=[i for i in range(0,5,1)]
print(rang_list)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0, 1, 2, 3, 4]


# ```np.linspace```
#### Return evenly spaced numbers over a specified interval.

In [ ]:
linspace_array = np.linspace(0, 2, 5)
print(linspace_array)

# ```np.zeros``` & ```np.like_zeros```

In [ ]:
zeros=np.zeros((5,5),dtype=np.int64)
print(zeros)



# ```np.ones``` & ```np.ones_like```

In [27]:
ones=np.ones((5,5))
print(ones)
print(ones.dtype)

arrs=np.array([raw1,raw2])
print(arrs)
ones_like_arrs=np.ones_like(arrs)
print(ones_like_arrs)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64
[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


## ```np.empty``` & ```np.empty_like``` 
<div dir="rtl" style="text-align: right; line-height: 1.8; font-family: 'Arial', sans-serif; padding: 10px; border-right: 5px solid #2196F3; ">
  <p>
    دالة <code >np.empty</code> 
    هي وسيلة تقنية متقدمة في مكتبة <b>NumPy</b>، حيث تقوم بـ 
    <strong>حجز مساحة في الذاكرة فقط</strong> 
    دون القيام بأي عملية تهيئة (Initialization) أو مسح للبيانات السابقة.
  </p>
  <p>
    ونتيجة لذلك، تظل العناصر بداخلها محتفظة بما يسمى 
    <span style="color: #1976D2;"><b> (Garbage Values)</b></span>، 
    وهي بقايا برمجية كانت موجودة في الذاكرة مسبقاً قبل عملية التخصيص. 
  </p>
</div>

In [ ]:
try_empty=np.empty((2,3))
print(try_empty)

try_empty_like=np.empty_like(arrs)
print(try_empty_like)

# ```np.full``` & ```np.full_like```

In [38]:
full_arr = np.full((3, 3), 7)
print(full_arr)

full_like_arr=np.full_like(arrs,5)
print(full_like_arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[5 5 5]
 [5 5 5]]


<table border="1" style="width:100%; border-collapse: collapse; font-family: Arial, sans-serif; margin-bottom: 20px;">
  <thead>
    <tr style="text-align: left;">
      <th style="padding: 12px; border: 1px solid #ddd;">Feature</th>
      <th style="padding: 12px; border: 1px solid #ddd;"><code>np.identity</code></th>
      <th style="padding: 12px; border: 1px solid #ddd;"><code>np.eye</code></th>
    </tr>
  
  <tbody>
    <tr>
      <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Matrix Shape</td>
      <td style="padding: 10px; border: 1px solid #ddd;">Always <b>Square</b> (n x n).</td>
      <td style="padding: 10px; border: 1px solid #ddd;">Can be <b>Rectangular</b> (N x M) or Square.</td>
    </tr>
    <tr>
      <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Diagonal Control (k)</td>
      <td style="padding: 10px; border: 1px solid #ddd;">Not supported (Always the main diagonal).</td>
      <td style="padding: 10px; border: 1px solid #ddd;">Supported (Can shift diagonal up or down).</td>
    </tr>
    <tr>
      <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Parameters</td>
      <td style="padding: 10px; border: 1px solid #ddd;">Takes a single integer <code>n</code>.</td>
      <td style="padding: 10px; border: 1px solid #ddd;">Takes <code>N</code> (rows), <code>M</code> (cols), and <code>k</code> (index).</td>
    </tr>
    <tr>
      <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Mathematical Concept</td>
      <td style="padding: 10px; border: 1px solid #ddd;">Pure <b>Identity Matrix</b> representation.</td>
      <td style="padding: 10px; border: 1px solid #ddd;">General purpose <b>Diagonal Matrix</b> creator.</td>
    </tr>
  </tbody>
</table>

In [ ]:
id_matrix = np.identity(3)
print("Identity Matrix (3x3):\n", id_matrix)

eye_rect = np.eye(3, 4)
print("\nEye Rectangular (3x4):\n", eye_rect)

eye_offset = np.eye(3, 3, k=1)  # k=0,1,2,.. means the diagonal above the main diagonal
print("\nEye with Offset (k=1):\n", eye_offset)

Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Eye Rectangular (3x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Eye with Offset (k=1):
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# type casting

In [4]:
typing_arr=np.array([1,2,3],dtype=np.float64)
print(typing_arr)

[1. 2. 3.]


In [5]:
astype_arr=typing_arr.astype(np.int64)
print(astype_arr)

[1 2 3]


In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr.dtype

float_arr = arr.astype(np.float64)
float_arr

In [8]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

print(int_array.astype(calibers.dtype))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#  NumPy data types
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Type code</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>int8, uint8</code></td>
<td style="text-align: left;"><code>i1, u1</code></td>
<td style="text-align: left;">Signed and unsigned 8-bit (1 byte) integer types</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>int16, uint16</code></td>
<td style="text-align: left;"><code>i2, u2</code></td>
<td style="text-align: left;">Signed and unsigned 16-bit integer types</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>int32, uint32</code></td>
<td style="text-align: left;"><code>i4, u4</code></td>
<td style="text-align: left;">Signed and unsigned 32-bit integer types</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>int64, uint64</code></td>
<td style="text-align: left;"><code>i8, u8</code></td>
<td style="text-align: left;">Signed and unsigned 64-bit integer types</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>float16</code></td>
<td style="text-align: left;"><code>f2</code></td>
<td style="text-align: left;">Half-precision floating point</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>float32</code></td>
<td style="text-align: left;"><code>f4 or f</code></td>
<td style="text-align: left;">Standard single-precision floating point; compatible with C float</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>float64</code></td>
<td style="text-align: left;"><code>f8 or d</code></td>
<td style="text-align: left;">Standard double-precision floating point; compatible with C double and Python <code>float</code> object</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>float128</code></td>
<td style="text-align: left;"><code>f16 or g</code></td>
<td style="text-align: left;">Extended-precision floating point</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>complex64</code>, <code>complex128</code>, <code>complex256</code></td>
<td style="text-align: left;"><code>c8, c16, c32</code></td>
<td style="text-align: left;">Complex numbers represented by two 32, 64, or 128 floats, respectively</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>bool</code></td>
<td style="text-align: left;">?</td>
<td style="text-align: left;">Boolean type storing <code>True</code> and <code>False</code> values</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>object</code></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">Python object type; a value can be any Python object</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>string_</code></td>
<td style="text-align: left;">S</td>
<td style="text-align: left;">Fixed-length ASCII string type (1 byte per character); for example, to create a string data type with length 10, use <code>'S10'</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>unicode_</code></td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">Fixed-length Unicode type (number of bytes platform specific); same specification semantics as <code>string_</code> (e.g., <code>'U10'</code>)</td>
</tr>
</tbody>
</table>

# Arithmetic with NumPy Arrays

In [20]:
arr1= np.array([[1., 2., 3.], [4., 5., 6.]])
arr2= np.array([[2,4,1],[3,2,4]])
print(f"{arr1+arr2}\n")
print(f"{arr1-arr2}\n")
print(f"{arr1*arr2}\n")
print(f"{arr1/arr2}\n")

[[ 3.  6.  4.]
 [ 7.  7. 10.]]

[[-1. -2.  2.]
 [ 1.  3.  2.]]

[[ 2.  8.  3.]
 [12. 10. 24.]]

[[0.5        0.5        3.        ]
 [1.33333333 2.5        1.5       ]]



# Logic with NumPy Arrays

In [24]:
print(arr1>arr2)
print(arr1<arr2)
print(arr1==arr2)
print(arr1!=arr2)
print(arr1>2)
print(arr1[arr1>2])

[[False False  True]
 [ True  True  True]]
[[ True  True False]
 [False False False]]
[[False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]]
[[False False  True]
 [ True  True  True]]
[3. 4. 5. 6.]


<table border="1" style="width:100%; border-collapse: collapse; font-family: Arial, sans-serif; margin-bottom: 20px;">
  <thead>
    <tr style="background-color: #fce4ec; text-align: left;">
      <th style="padding: 12px; border: 1px solid #ddd;">Operation Type</th>
      <th style="padding: 12px; border: 1px solid #ddd;">Behavior in NumPy</th>
      <th style="padding: 12px; border: 1px solid #ddd;">Example Result</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Arithmetic (+, -, *, /)</td>
      <td style="padding: 10px; border: 1px solid #ddd;">Performed <b>Element-wise</b>.</td>
      <td style="padding: 10px; border: 1px solid #ddd;">[1, 2] * [3, 4] = [3, 8]</td>
    </tr>
    <tr>
      <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Logical (>, <, ==)</td>
      <td style="padding: 10px; border: 1px solid #ddd;">Returns a <b>Boolean Array</b>.</td>
      <td style="padding: 10px; border: 1px solid #ddd;">[10, 5] > 7 = [True, False]</td>
    </tr>
    </tr>
  </tbody>
</table>

# Indexing and Slicing

In [25]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
print(arr[:5])
print(arr[5:])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[0 1 2 3 4]
[5 6 7 8 9]


In [29]:
arr[5]=15
print(arr)
arr[6:9] = 12
print(arr)


[ 0  1  2  3  4 15 12 12  8  9]
[ 0  1  2  3  4 15 12 12 12  9]


In [26]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[0] = 99
print(arr)

[5 6 7]
[ 0  1  2  3  4 99  6  7  8  9]


In [ ]:
arr_slice[1] = 12345
print(arr)

In [ ]:
arr_slice[:] = 64
print(arr)

In [37]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0])  # First row
print(arr2d[1])  # Second row
print(arr2d[2])  # Third row

print(arr2d[0][0])  # First row, first column
print(arr2d[1][2])  # Second row, third column
print(arr2d[2][1])  # Third row, second column

[1 2 3]
[4 5 6]
[7 8 9]
1
6
8


![](https://towardsdatascience.com/wp-content/uploads/2024/09/13dU9q5YC8u8a3nvMxVHGzQ.png)
<p style="text-align:center;">
  <img src="https://towardsdatascience.com/wp-content/uploads/2024/09/13dU9q5YC8u8a3nvMxVHGzQ.pn" alt="NumPy axis" width="400" height="40
      0">
</p>

In [31]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d[0])  # First 2D array
print(arr3d[1])  # Second 2D array
print(arr3d[0][0])  # First 2D array, first row
print(arr3d[0][1])  # First 2D array, second row
print(arr3d[1][0])  # Second 2D array, first row
print(arr3d[1][1])  # Second 2D array, second row   

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[1 2]
[3 4]
[5 6]
[7 8]


In [32]:
old_values = arr3d[0].copy()
print("Old values:\n", old_values)
arr3d[0] = 0
print("Modified arr3d:\n", arr3d)
print("Old values after modification:\n", old_values)

Old values:
 [[1 2]
 [3 4]]
Modified arr3d:
 [[[0 0]
  [0 0]]

 [[5 6]
  [7 8]]]
Old values after modification:
 [[1 2]
 [3 4]]


In [33]:
arr3d[1, 0]

array([5, 6])

# Indexing with slices

In [ ]:
print(arr2d)
print(arr2d[:2]) # First two rows
print(arr2d[:2, 1:]) # First two rows, all columns starting from the second column
print(arr2d[:2, 2])  # First two rows, third column
print( arr2d[:, :1]) # All rows, first column


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [43]:
lower_dim_slice = arr2d[1, :2]
print(lower_dim_slice)
print(lower_dim_slice.shape)

[4 5]
(2,)


![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRA5_cwKdkTF40D06Y_RdaItlUdbdamY4HFA&)

# Boolean Indexing

In [44]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [46]:
print(names == "Bob")
print( data[names == "Bob"])

[ True False False  True False False False]
[[4 7]
 [0 0]]


In [ ]:
print( data[names == "Bob", 1:])
print( data[names == "Bob", 1])

[[7]
 [0]]
[7 0]


In [49]:
print(names != "Bob")

[False  True  True False  True  True  True]


## Boolean arithmetic operators like `&` (and) `|` (or)

In [51]:
mask = (names == "Bob") | (names == "Will")
print(mask)
print(data[mask])

[ True False  True  True  True False False]
[[ 4  7]
 [-5  6]
 [ 0  0]
 [ 1  2]]


In [52]:
data[data < 0] = 0
print(data)

[[4 7]
 [0 2]
 [0 6]
 [0 0]
 [1 2]
 [0 0]
 [3 4]]


In [ ]:

data[names != "Joe"] = 7
data

array([5, 6])

# Fancy Indexing
Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [54]:
arr = np.zeros((8, 4))
print(arr)
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


## select a subset of the rows in a particular order

In [ ]:
print(arr[[4, 3, 0, 6]])
print(arr[[-3, -5, -7]])

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [63]:
arr6 = np.arange(32)
print(arr6)
print(arr6.reshape(8, 4))
print(arr6.reshape(4, 8))
print(arr6.reshape(2, 16))
print(arr6.reshape(4, -1))  # Automatically determine the number of columns
print(arr6.reshape(-1, 4))  # Automatically determine the number of rows

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [70]:
arr7 = arr6.reshape(8, 4)
print(arr7[[1, 5, 7, 2], [0, 3, 1, 2]])

print(arr7[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[ 4 23 29 10]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [ ]:
print(arr7[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

arr7[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
print(arr7)

# Transposing Arrays and Swapping Axe

Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything. Arrays have the `transpose` method and the special `T` attribute:

In [ ]:
arr8 = np.arange(15).reshape((3, 5))
print(f"arr8 = {arr8} \n")
print(arr8.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


# matrix multiplication

In [79]:
np.dot(arr8.T, arr8)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [80]:
arr8.T @ arr8

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

## swapping axes
le transposing with `.T` is a special case of swapping axes. ndarray has the method `swapaxes`, which takes a pair of axis numbers and switches the indicated axes to rearrange the data

In [85]:
print(f"arr8 = \n {arr8} \n")
arr8.swapaxes(0, 1)

arr8 = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 



array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#  Pseudorandom Number Generation

The `numpy.random` module supplements the built-in Python `random` module with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions. For example, you can get a 4 × 4 array of samples from the standard normal distribution using `numpy.random.standard_normal`

In [86]:
samples = np.random.standard_normal(size=(4, 4))
print(samples)

[[ 0.18442541 -0.11369954  0.42348685 -0.47856969]
 [ 1.02906241 -0.75820361  0.82413284  0.59479947]
 [ 0.42817786  0.83908111 -0.38024986 -0.01807586]
 [-0.54119613  1.16730113  0.97949318  1.39582471]]


In [ ]:
random_array = np.random.rand(3)
print(random_array)

random_array = np.random.random((3, 3))
print(random_array)

random_integers = np.random.randint(1, 10, (2, 2))
print(random_integers)


# NumPy random number generator methods

<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>permutation</code></td>
<td style="text-align: left;">Return a random permutation of a sequence, or return a permuted range</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>shuffle</code></td>
<td style="text-align: left;">Randomly permute a sequence in place</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>uniform</code></td>
<td style="text-align: left;">Draw samples from a uniform distribution</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>integers</code></td>
<td style="text-align: left;">Draw random integers from a given low-to-high range</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>standard_normal</code></td>
<td style="text-align: left;">Draw samples from a normal distribution with mean 0 and standard deviation 1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>binomial</code></td>
<td style="text-align: left;">Draw samples from a binomial distribution</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>normal</code></td>
<td style="text-align: left;">Draw samples from a normal (Gaussian) distribution</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>beta</code></td>
<td style="text-align: left;">Draw samples from a beta distribution</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>chisquare</code></td>
<td style="text-align: left;">Draw samples from a chi-square distribution</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>gamma</code></td>
<td style="text-align: left;">Draw samples from a gamma distribution</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>uniform</code></td>
<td style="text-align: left;">Draw samples from a uniform [0, 1) distribution</td>
</tr>
</tbody>
</table>

# Universal Functions (Ufunc)

## unary ufuncs

In [ ]:
arr = np.arange(10)
print(np.sqrt(arr))
print(np.exp(arr))

# unary universal functions
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Function</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>abs, fabs</code></td>
<td style="text-align: left;">Compute the absolute value element-wise for integer, floating-point, or complex values</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>sqrt</code></td>
<td style="text-align: left;">Compute the square root of each element (equivalent to <code>arr ** 0.5</code>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>square</code></td>
<td style="text-align: left;">Compute the square of each element (equivalent to <code>arr ** 2</code>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>exp</code></td>
<td style="text-align: left;">Compute the exponent e<sup>x</sup> of each element</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>log, log10, log2, log1p</code></td>
<td style="text-align: left;">Natural logarithm (base <em>e</em>), log base 10, log base 2, and log(1 + x), respectively</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>sign</code></td>
<td style="text-align: left;">Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>ceil</code></td>
<td style="text-align: left;">Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>floor</code></td>
<td style="text-align: left;">Compute the floor of each element (i.e., the largest integer less than or equal to each element)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>rint</code></td>
<td style="text-align: left;">Round elements to the nearest integer, preserving the <code>dtype</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>modf</code></td>
<td style="text-align: left;">Return fractional and integral parts of array as separate arrays</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>isnan</code></td>
<td style="text-align: left;">Return Boolean array indicating whether each value is <code>NaN</code> (Not a Number)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>isfinite, isinf</code></td>
<td style="text-align: left;">Return Boolean array indicating whether each element is finite (non-<code>inf</code>, non-<code>NaN</code>) or infinite, respectively</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>cos, cosh, sin, sinh, tan, tanh</code></td>
<td style="text-align: left;">Regular and hyperbolic trigonometric functions</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>arccos, arccosh, arcsin, arcsinh, arctan, arctanh</code></td>
<td style="text-align: left;">Inverse trigonometric functions</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>logical_not</code></td>
<td style="text-align: left;">Compute truth value of <code>not</code> <code>x</code> element-wise (equivalent to <code>~arr</code>)</td>
</tr>
</tbody>
</table>

## binary ufunc

In [ ]:
x = np.random.standard_normal(8)
y = np.random.standard_normal(8)
print(x)
print(y)
print(np.maximum(x, y))

[-0.08041748  1.0219201  -0.90868549 -1.53687366 -0.0543977   1.01478098
 -0.18072152  0.2261801 ] [ 1.14984898  0.14260327 -2.62027967 -0.66551022  2.63509355  2.10664573
 -0.11349274  0.77492499]


# binary universal functions
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Function</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>add</code></td>
<td style="text-align: left;">Add corresponding elements in arrays</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>subtract</code></td>
<td style="text-align: left;">Subtract elements in second array from first array</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>multiply</code></td>
<td style="text-align: left;">Multiply array elements</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>divide, floor_divide</code></td>
<td style="text-align: left;">Divide or floor divide (truncating the remainder)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>power</code></td>
<td style="text-align: left;">Raise elements in first array to powers indicated in second array</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>maximum, fmax</code></td>
<td style="text-align: left;">Element-wise maximum; <code>fmax</code> ignores <code>NaN</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>minimum, fmin</code></td>
<td style="text-align: left;">Element-wise minimum; <code>fmin</code> ignores <code>NaN</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>mod</code></td>
<td style="text-align: left;">Element-wise modulus (remainder of division)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>copysign</code></td>
<td style="text-align: left;">Copy sign of values in second argument to values in first argument</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>greater, greater_equal, less, less_equal, equal, not_equal</code></td>
<td style="text-align: left;">Perform element-wise comparison, yielding Boolean array (equivalent to infix operators <code>&gt;, &gt;=, &lt;, &lt;=, ==, !=</code>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>logical_and</code></td>
<td style="text-align: left;">Compute element-wise truth value of AND (<code>&amp;</code>) logical operation</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>logical_or</code></td>
<td style="text-align: left;">Compute element-wise truth value of OR (<code>|</code>) logical operation</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>logical_xor</code></td>
<td style="text-align: left;">Compute element-wise truth value of XOR (<code>^</code>) logical operation</td>
</tr>
</tbody>
</table>

# array statistical methods

In [92]:
arr = np.random.standard_normal((5, 4))
print(arr.mean())
print(arr.sum())
print(arr.sum(axis=0))  # Sum of each column
print(arr.sum(axis=1))  # Sum of each row

0.10161678736050064
2.0323357472100128
[ 2.30175239 -0.86518709  1.59838591 -1.00261547]
[-0.37734552  1.80118208  1.23342167 -1.82815769  1.20323522]


<table class="table">
<caption>Basic array statistical methods</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>sum</code></td>
<td style="text-align: left;">Sum of all the elements in the array or along an axis; zero-length arrays have sum 0</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>mean</code></td>
<td style="text-align: left;">Arithmetic mean; invalid (returns <code>NaN</code>) on zero-length arrays</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>std, var</code></td>
<td style="text-align: left;">Standard deviation and variance, respectively</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>min, max</code></td>
<td style="text-align: left;">Minimum and maximum</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>argmin, argmax</code></td>
<td style="text-align: left;">Indices of minimum and maximum elements, respectively</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>cumsum</code></td>
<td style="text-align: left;">Cumulative sum of elements starting from 0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>cumprod</code></td>
<td style="text-align: left;">Cumulative product of elements starting from 1</td>
</tr>
</tbody>
</table>

In [95]:
arr = np.random.standard_normal(100)
(arr > 0).sum()

np.int64(46)

Two additional methods, `any` and `all`, are useful especially for Boolean arrays. `any` tests whether one or more values in an array is `True`, while `all` checks if every value is `True`

In [ ]:
bools = np.array([False, False, True, False])

bools.any()

bools.all()

## ```.sort()```

In [96]:
arr.sort()


# File Input and Output with Arrays
NumPy is able to save and load data to and from disk in some text or binary formats.
```numpy.save``` and ```numpy.load``` are the two workhorse functions for efficiently <u>saving</u> and <u>loading</u> array data on disk. Arrays are saved by default in an uncompressed raw binary format with file <u>extension .npy</u>:

In [98]:
arr = np.arange(10)
np.save("some_array", arr)

In [ ]:
np.load("some_array.npy")

You can save multiple arrays in an uncompressed archive using ```numpy.savez``` and passing the arrays as keyword arguments:

In [ ]:
np.savez("array_archive.npz", a=arr, b=arr)


In [ ]:
arch = np.load("array_archive.npz")