* np.array
* asarray
* arange
* linspace
* ones & ones_like
* zeros& zeros_like
* empty & empty_like
* full & full_like
* eye & identity


* arithmatic with arrays
* logic with arrays
* indixing & slicing 
* arr.copy
* arr.shape
* arr.reshape
* arr.ndim


In [1]:
import numpy as np

In [2]:
ar=np.arange(0,10,.1)
ar

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [3]:
arr=np.linspace(0,10,5)
arr
#step=(stop-start)\num-1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

x=np.array([1,2,3])
x.reshape(3,1)


In [ ]:
x[ np.newaxis  ,   :   ]

x[  :  , np.newaxis  ]


# Array Splitting in NumPy

Splitting is the process of breaking a single array into multiple sub-arrays along a specific axis. This is essentially the **reverse operation of concatenation**. NumPy provides three specialized functions for this:

---

### 1. Vertical Splitting: `np.vsplit`
* **Behavior**: Splits an array into multiple sub-arrays vertically (row-wise).
* **Axis**: It operates along **axis 0**.
* **Condition**: The total number of rows must be divisible by the number of splits.

### 2. Horizontal Splitting: `np.hsplit`
* **Behavior**: Splits an array into multiple sub-arrays horizontally (column-wise).
* **Axis**: It operates along **axis 1**.
* **Condition**: The total number of columns must be divisible by the number of splits.

### 3. Depth Splitting: `np.dsplit`
* **Behavior**: Splits an array along the 3rd dimension (depth).
* **Axis**: It operates along **axis 2**.
* **Requirement**: Only works on arrays with 3 or more dimensions.

In [45]:
raw1=[10,20,30]
raw2=[40,50,60]
raw3=[70,80,90]

grid=np.array([raw1,raw2,raw3,raw1,raw2,raw1])

print(grid)
print("===========")
upper  , lower = np.vsplit(grid,[2])
print(upper)
print("===========")
print(lower)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [10 20 30]
 [40 50 60]
 [10 20 30]]
[[10 20 30]
 [40 50 60]]
[[70 80 90]
 [10 20 30]
 [40 50 60]
 [10 20 30]]


In [46]:
grid=np.array([[1,2,3,4,5],[5,6,8,7,8],[2,7,8,92,1],[5,6,6,7,8]])

print(grid)
left , right=np.hsplit(grid,[2])
print(left)
print("===========")
print(right)

[[ 1  2  3  4  5]
 [ 5  6  8  7  8]
 [ 2  7  8 92  1]
 [ 5  6  6  7  8]]
[[1 2]
 [5 6]
 [2 7]
 [5 6]]
[[ 3  4  5]
 [ 8  7  8]
 [ 8 92  1]
 [ 6  7  8]]


# Array Stacking in NumPy

Stacking is the process of joining multiple arrays along a new or existing axis. It is the core method for combining data from different sources into a single structure. NumPy provides three specialized functions for this:

---

### 1. Vertical Stacking: `np.vstack`
* **Behavior**: Stacks arrays on top of each other (row-wise).
* **Axis**: It operates along **axis 0**.
* **Requirement**: Arrays must have the same number of columns.
* **Result**: Increases the number of rows.

### 2. Horizontal Stacking: `np.hstack`
* **Behavior**: Stacks arrays side-by-side (column-wise).
* **Axis**: It operates along **axis 1**.
* **Requirement**: Arrays must have the same number of rows.
* **Result**: Increases the number of columns.

### 3. Depth Stacking: `np.dstack`
* **Behavior**: Stacks arrays along the third dimension (depth).
* **Axis**: It operates along **axis 2**.
* **Common Use**: Combining separate color channels (Red, Green, Blue) to create a full RGB image.

In [52]:
arr1=np.array([[1,2],[3,5]])
arr2=np.array([[7,2],[8,6]])
#print(arr1)
#print(arr2)
#np.concatenate
arr_col=np.concatenate((arr1,arr2),axis=0)
arr_col

array([[1, 2],
       [3, 5],
       [7, 2],
       [8, 6]])

In [56]:
arr_raw1=np.array(raw1)
arrr_raw2=np.array(raw2)
arr_raw1 , arrr_raw2

v_stack=np.vstack((arr_raw1,arrr_raw2))
v_stack
h_stack=np.hstack((arr_raw1,arrr_raw2))
h_stack


array([10, 20, 30, 40, 50, 60])

## Trace of a Matrix

In [62]:
grid_raws=np.array([raw1,raw2,raw3])
print(grid_raws)
result=np.trace(grid_raws)b
print(result)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
150


In [ ]:
v1 = np.array([1, 2])
v2 = np.array([3, 4])
# (1*3 )+(2*4)
np.dot(v1,v2)

A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

np.dot(A,B)
A @ B

# Transposing Arrays and Swapping Axe

Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything. Arrays have the `transpose` method and the special `T` attribute:

In [71]:
arr6=np.arange(15).reshape((3,5))
print(arr6)
print("=============")
print(arr6.T)
print("=============")
print(np.transpose(arr6))
print("=============")
print(arr6.swapaxes(0,1))
print("=============")


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


# Commonly used <code>np.linalg</code> functions
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Function</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>diag</code></td>
<td style="text-align: left;">Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>dot</code></td>
<td style="text-align: left;">Matrix multiplication</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>trace</code></td>
<td style="text-align: left;">Compute the sum of the diagonal elements</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>det</code></td>
<td style="text-align: left;">Compute the matrix determinant</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>eig</code></td>
<td style="text-align: left;">Compute the eigenvalues and eigenvectors of a square matrix</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>inv</code></td>
<td style="text-align: left;">Compute the inverse of a square matrix</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>pinv</code></td>
<td style="text-align: left;">Compute the Moore-Penrose pseudoinverse of a matrix</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>qr</code></td>
<td style="text-align: left;">Compute the QR decomposition</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>svd</code></td>
<td style="text-align: left;">Compute the singular value decomposition (SVD)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>solve</code></td>
<td style="text-align: left;">Solve the linear system Ax = b for x, where A is a square matrix</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>lstsq</code></td>
<td style="text-align: left;">Compute the least-squares solution to <code>Ax = b</code></td>
</tr>
</tbody>
</table>

3x+y=9
x+2y=8

In [72]:
A=np.array([[3,1],[1,2]])
B=np.array([9,8])

solution=np.linalg.solve(A,B)
solution
x_value=solution[0]
y_vlaue=solution[1]


array([2., 3.])

In [74]:
matrix = np.array([[4, 6],
                   [3, 8]])
deter=np.linalg.det(matrix)

np.round(deter)

np.float64(14.0)

In [ ]:
matrix_2 = np.array([[1, 2],
                   [3, 4]])
inverse_matrix=np.linalg.inv(matrix_2)

In [87]:
rand=np.random.rand(3)
rand
rand0=np.random.random((3,3))
rand1=np.random.randint(1,10,(2,2))
rand1
np.random.seed(2)
rand10=np.random.randint(1,10,(2,2))
rand10

array([[9, 9],
       [7, 3]])

# Universal Functions (Ufunc)
## unary UFUNC
## binary UFUNC

In [109]:
arr=np.arange(10)
print(np.sqrt(arr))
print(np.exp(arr))
print(np.square(arr))

arr2=np.arange(-5,10)
print(arr2)
print(np.abs(arr2))
#print(np.log(arr+1)

data = np.array([-1, 0, 1, 2, np.pi/2])

cos_cal=np.cos(data)
sin_val=np.sin(data)
print(cos_cal)

round_arr=np.array([1.2,1.5,1.8])

ceil_val=np.ceil(round_arr)
floor_vlue=np.floor(round_arr)
round_value=np.round(round_arr)
round_value

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 0  1  4  9 16 25 36 49 64 81]
[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9]
[5 4 3 2 1 0 1 2 3 4 5 6 7 8 9]
[ 5.40302306e-01  1.00000000e+00  5.40302306e-01 -4.16146837e-01
  6.12323400e-17]


array([1., 2., 2.])

In [107]:
x=np.array([5,6,2,7,9])
y=np.array([2,9,3,8,2])

print(np.maximum(x,y))
print(np.minimum(x,y))
print(np.add(x,y))
print(np.multiply(x,y))
print(np.power(x,2))


[5 9 3 8 9]
[2 6 2 7 2]
[ 7 15  5 15 11]
[10 54  6 56 18]
[25 36  4 49 81]


#  Some unary universal functions
<table class="table">

<thead>
<tr class="header">
<th style="text-align: left;">Function</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>abs, fabs</code></td>
<td style="text-align: left;">Compute the absolute value element-wise for integer, floating-point, or complex values</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>sqrt</code></td>
<td style="text-align: left;">Compute the square root of each element (equivalent to <code>arr ** 0.5</code>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>square</code></td>
<td style="text-align: left;">Compute the square of each element (equivalent to <code>arr ** 2</code>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>exp</code></td>
<td style="text-align: left;">Compute the exponent e<sup>x</sup> of each element</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>log, log10, log2, log1p</code></td>
<td style="text-align: left;">Natural logarithm (base <em>e</em>), log base 10, log base 2, and log(1 + x), respectively</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>sign</code></td>
<td style="text-align: left;">Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>ceil</code></td>
<td style="text-align: left;">Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>floor</code></td>
<td style="text-align: left;">Compute the floor of each element (i.e., the largest integer less than or equal to each element)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>rint</code></td>
<td style="text-align: left;">Round elements to the nearest integer, preserving the <code>dtype</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>modf</code></td>
<td style="text-align: left;">Return fractional and integral parts of array as separate arrays</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>isnan</code></td>
<td style="text-align: left;">Return Boolean array indicating whether each value is <code>NaN</code> (Not a Number)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>isfinite, isinf</code></td>
<td style="text-align: left;">Return Boolean array indicating whether each element is finite (non-<code>inf</code>, non-<code>NaN</code>) or infinite, respectively</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>cos, cosh, sin, sinh, tan, tanh</code></td>
<td style="text-align: left;">Regular and hyperbolic trigonometric functions</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>arccos, arccosh, arcsin, arcsinh, arctan, arctanh</code></td>
<td style="text-align: left;">Inverse trigonometric functions</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>logical_not</code></td>
<td style="text-align: left;">Compute truth value of <code>not</code> <code>x</code> element-wise (equivalent to <code>~arr</code>)</td>
</tr>
</tbody>
</table>

# binary universal functions
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Function</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>add</code></td>
<td style="text-align: left;">Add corresponding elements in arrays</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>subtract</code></td>
<td style="text-align: left;">Subtract elements in second array from first array</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>multiply</code></td>
<td style="text-align: left;">Multiply array elements</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>divide, floor_divide</code></td>
<td style="text-align: left;">Divide or floor divide (truncating the remainder)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>power</code></td>
<td style="text-align: left;">Raise elements in first array to powers indicated in second array</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>maximum, fmax</code></td>
<td style="text-align: left;">Element-wise maximum; <code>fmax</code> ignores <code>NaN</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>minimum, fmin</code></td>
<td style="text-align: left;">Element-wise minimum; <code>fmin</code> ignores <code>NaN</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>mod</code></td>
<td style="text-align: left;">Element-wise modulus (remainder of division)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>copysign</code></td>
<td style="text-align: left;">Copy sign of values in second argument to values in first argument</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>greater, greater_equal, less, less_equal, equal, not_equal</code></td>
<td style="text-align: left;">Perform element-wise comparison, yielding Boolean array (equivalent to infix operators <code>&gt;, &gt;=, &lt;, &lt;=, ==, !=</code>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>logical_and</code></td>
<td style="text-align: left;">Compute element-wise truth value of AND (<code>&amp;</code>) logical operation</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>logical_or</code></td>
<td style="text-align: left;">Compute element-wise truth value of OR (<code>|</code>) logical operation</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>logical_xor</code></td>
<td style="text-align: left;">Compute element-wise truth value of XOR (<code>^</code>) logical operation</td>
</tr>
</tbody>
</table>

# array statistical methods

In [120]:
data = np.array([[10, 20, 30], 
                 [40, 50, 60], 
                 [70, 80, 90]])

mean_val=np.mean(data)
median_val=np.median(data)
std_val=np.std(data)
var_val=np.var(data)
min_val=np.min(data)
max_val=np.max(data)
sum_val=np.sum(data)
prod_val=np.prod(data)


np.int64(362880000000000)

<table class="table">
<caption>Basic array statistical methods</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>sum</code></td>
<td style="text-align: left;">Sum of all the elements in the array or along an axis; zero-length arrays have sum 0</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>mean</code></td>
<td style="text-align: left;">Arithmetic mean; invalid (returns <code>NaN</code>) on zero-length arrays</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>std, var</code></td>
<td style="text-align: left;">Standard deviation and variance, respectively</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>min, max</code></td>
<td style="text-align: left;">Minimum and maximum</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>argmin, argmax</code></td>
<td style="text-align: left;">Indices of minimum and maximum elements, respectively</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>cumsum</code></td>
<td style="text-align: left;">Cumulative sum of elements starting from 0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>cumprod</code></td>
<td style="text-align: left;">Cumulative product of elements starting from 1</td>
</tr>
</tbody>
</table>

Two additional methods, `any` and `all`, are useful especially for Boolean arrays. `any` tests whether one or more values in an array is `True`, while `all` checks if every value is `True`

In [126]:
boolean_arr=np.array([1,1,1])
boolean_arr.any()   # like logic or 
boolean_arr.all() # like logic and

failed_value=not np.all(boolean_arr)
failed_value

False

In [1]:
import numpy as np

In [5]:
np.random.seed(0)
mmmmm=np.random.randint(2,12,10)
print(mmmmm)
print(np.sort(mmmmm))

[ 7  2  5  5  9 11  5  7  4  6]
[ 2  4  5  5  5  6  7  7  9 11]


In [2]:
np.random.seed(1)
M2=np.random.randint(2,20,10)
print(M2)

[ 7 13 14 10 11 13  7 17  2 18]


In [3]:
np.save("M2_file",M2)


In [6]:
np.savez("ARRAYS",a=mmmmm,b=M2)

In [7]:
larray=np.load("M2_file.npy")
larray

array([ 7, 13, 14, 10, 11, 13,  7, 17,  2, 18])

In [10]:
varsx=np.load("ARRAYS.npz")

print(varsx.files)
print(varsx['a'])
print(varsx['b'])

['a', 'b']
[ 7  2  5  5  9 11  5  7  4  6]
[ 7 13 14 10 11 13  7 17  2 18]
