# Numpy arrays

**install numpy**

In [4]:
!pip install numpy

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [2]:
import numpy as np


In [17]:
print(np.__version__)

2.1.3


# creating a 1D NUMPY array

In [40]:
arr1=np.array(([1,2,3,4,5]))
print(arr1)

[1 2 3 4 5]


# creating a 2D NUMPY array

In [49]:
arr2=np.array([[0,1,3],[2,6,8],[50,60,70]])
print(arr2)

int64


## ndim 

In [27]:
a= np.array(50)  # 0 dim
b= np.array([1,2,3,4,5]) #1-D
c= np.array([[0,1,3],[2,6,8]]) # 2-d
d= np.array([                      #3-D
            [
             [1,2,3],[5,6,7],[8,9,10]   
            ]
            ])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [47]:
zeros=np.zeros((5,5),dtype=np.int64)
print(zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [3]:
ones=np.ones((5,5))
print(ones)
print(ones.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64


In [52]:
aranged_arr=np.arange(10)
rang_arr=[i for i in range(10)]
print(aranged_arr)
print(rang_arr)


[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


`range(start,stop,step)`


In [5]:
range_step=np.arange(0,5,.5)
print(range_step)
rang_list=[i for i in range(0,5,1)]
print(rang_list)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0, 1, 2, 3, 4]
